"""
The Scribe — Report Generator
==============================
Consumes the final MatchState (scout stats, rag context, tactician analysis)
and generates three tailored reports using an asyncio parallel round-by-round pipeline.
"""

import asyncio
import json
import logging
import os
from typing import Any

from google import genai
from google.genai import types

logger = logging.getLogger(__name__)


async def analyze_round_flash(
    client: genai.Client, round_num: int, round_data: dict, map_playbook: dict, rag_context: list
) -> str:
    """Stage 1: Low-latency round analysis using Gemini 2.5 Flash."""
    prompt = f"""
    You are an elite CS2 tactical analyst. Analyze this specific round.
    Map Playbook Context: {json.dumps(map_playbook)}
    Historical Pro Context (RAG): {json.dumps(rag_context)}

    Round Data: {json.dumps(round_data)}

    Return a concise, tactical 2-3 sentence summary of what happened in this round, focusing on positioning, utility usage, and critical errors.
    """
    try:
        response = await client.aio.models.generate_content(
            model="gemini-2.5-flash", contents=prompt
        )
        return f"Round {round_num}: {response.text}"
    except Exception as e:
        logger.error(f"Round {round_num} analysis failed: {e}")
        return f"Round {round_num}: Analysis failed."


async def async_generate_reports(
    match_id: str, scout_out: dict, rag_context: list, tactical_analysis: dict, map_playbook: dict
) -> dict[str, Any]:
    """Docstring for async_generate_reports."""
    api_key = os.environ.get("GEMINI_API_KEY") or os.environ.get("GOOGLE_API_KEY")
    if not api_key:
        logger.warning("No Gemini API key found for report generation.")
        return _stub_reports()

    client = genai.Client(api_key=api_key)

    # 1. Group data by round
    rounds_data = {}
    if "round_history" in scout_out:
        for r in scout_out["round_history"]:
            rn = r["round_num"]
            rounds_data[rn] = {"summary": r}

    # Optional: Attach kills to rounds if available in scout_out
    # Since scout_out has "first_contacts", "rounds", etc. inside tactical_analysis or scout_out

    # 2. Stage 1: Run 24x Parallel Round Calls
    tasks = []
    for rn, r_data in rounds_data.items():
        tasks.append(analyze_round_flash(client, rn, r_data, map_playbook, rag_context))

    round_summaries = await asyncio.gather(*tasks)

    # 3. Stage 2: Synthesis Call
    user_team = scout_out.get("uploader_team_label") or scout_out.get("user_team")
    user_notes = scout_out.get("user_notes")
    uploader_steam_id = scout_out.get("uploader_steam_id")
    is_recon = scout_out.get("is_recon", False)

    from db.config import get_config

    scribe_base = get_config("prompt_scribe_base", "You are an elite CS2 coach.")
    focus_prompt_template = get_config("prompt_focus_instruction", "Focus on {user_team}.")
    recon_prompt = get_config("prompt_recon_instruction", "Focus on recon scan.")

    focus_instruction = (
        recon_prompt
        if is_recon
        else focus_prompt_template.format(user_team=user_team, uploader_steam_id=uploader_steam_id)
        if user_team
        else ""
    )
    notes_instruction = f"\nCRITICAL COACH NOTES: {user_notes}\n" if user_notes else ""

    synthesis_prompt = f"""
    {scribe_base}
    {focus_instruction}
    {notes_instruction}

    Here is the detailed round-by-round analysis generated by the parallel agents:
    {" ".join(round_summaries)}

    Generate a JSON object containing the following reports based on the round summaries and overall tactical patterns:
    1. "individual_report": A markdown string focused exclusively on the uploader ({uploader_steam_id}).
    2. "team_report": A markdown string focused on the team's structure and overall round flow.
    3. "player_reports": A dictionary mapping player names to their individual constructive markdown reports.
    4. "strat_card": Legacy field - populate this with the same markdown as "team_report".
    5. "coach_report": Legacy field - populate this with a summary of tactical errors.

    Ensure the output is valid JSON matching this schema exactly:
    {{
        "individual_report": "markdown string",
        "team_report": "markdown string",
        "player_reports": {{ "PlayerName": "markdown string" }},
        "strat_card": "markdown string",
        "coach_report": "markdown string"
    }}
    """

    try:
        response = await client.aio.models.generate_content(
            model="gemini-2.5-pro",
            contents=synthesis_prompt,
            config=types.GenerateContentConfig(
                response_mime_type="application/json", temperature=0.4
            ),
        )
        return json.loads(response.text)
    except Exception as e:
        logger.error(f"Synthesis failed: {e}")
        return _stub_reports()


def generate_reports(
    match_id: str, scout_out: dict, rag_context: list, tactical_analysis: dict
) -> dict[str, Any]:
    """Synchronous wrapper for LangGraph."""
    # Fetch map playbook from DB
    from db.database import SessionLocal
    from db.models import MapPlaybook

    map_playbook = {}
    map_name = scout_out.get("map_name", "unknown")
    db = SessionLocal()
    try:
        pb = db.query(MapPlaybook).filter_by(map_name=f"de_{map_name}").first()
        if not pb:
            pb = db.query(MapPlaybook).filter_by(map_name=map_name).first()
        if pb:
            map_playbook = json.loads(pb.playbook_json)
    except Exception as e:
        logger.warning(f"Could not load map playbook: {e}")
    finally:
        db.close()

    return asyncio.run(
        async_generate_reports(match_id, scout_out, rag_context, tactical_analysis, map_playbook)
    )


def _stub_reports() -> dict[str, Any]:
    """Docstring for _stub_reports."""
    return {
        "individual_report": "### Individual Report\nAI coaching requires GEMINI_API_KEY.",
        "team_report": "### Team Report\nAI coaching requires GEMINI_API_KEY.",
        "player_reports": {},
        "strat_card": "### Strat Card\nAI coaching requires GEMINI_API_KEY.",
        "coach_report": "### Coach Report\nAI coaching requires GEMINI_API_KEY.",
    }
