"""Initial schema

Revision ID: 8b072a51f688
Revises: 
Create Date: 2026-07-28 14:15:18.363401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b072a51f688'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_embeddings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_embeddings_source'), 'knowledge_embeddings', ['source'], unique=False)
    op.create_table('linked_accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('provider_user_id', sa.String(length=64), nullable=False),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linked_accounts_user_id'), 'linked_accounts', ['user_id'], unique=False)
    op.create_table('map_playbooks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('map_name', sa.String(length=64), nullable=False),
    sa.Column('playbook_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_map_playbooks_map_name'), 'map_playbooks', ['map_name'], unique=True)
    op.create_table('system_configs',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('teams',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('owner_user_id', sa.String(length=64), nullable=False),
    sa.Column('invite_code', sa.String(length=16), nullable=False),
    sa.Column('logo_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_invite_code'), 'teams', ['invite_code'], unique=True)
    op.create_index(op.f('ix_teams_owner_user_id'), 'teams', ['owner_user_id'], unique=False)
    op.create_table('user_strategies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('map_name', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('strategy_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_strategies_map_name'), 'user_strategies', ['map_name'], unique=False)
    op.create_index(op.f('ix_user_strategies_user_id'), 'user_strategies', ['user_id'], unique=False)
    op.create_table('matches',
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('match_name', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.String(length=64), nullable=True),
    sa.Column('team_id', sa.String(length=36), nullable=True),
    sa.Column('demo_filename', sa.String(length=255), nullable=True),
    sa.Column('map_name', sa.String(length=64), nullable=False),
    sa.Column('tickrate', sa.Integer(), nullable=False),
    sa.Column('total_rounds', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PARSING', 'COMPLETE', 'FAILED', name='matchstatus'), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('coaching_notes', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('uploader_steam_id', sa.String(length=32), nullable=True),
    sa.Column('is_recon', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('gcs_demo_uri', sa.Text(), nullable=True),
    sa.Column('gcs_audio_uri', sa.Text(), nullable=True),
    sa.Column('gcs_parsed_uri', sa.Text(), nullable=True),
    sa.Column('player_stats_json', sa.Text(), nullable=True),
    sa.Column('parse_duration_seconds', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_index(op.f('ix_matches_team_id'), 'matches', ['team_id'], unique=False)
    op.create_index(op.f('ix_matches_user_id'), 'matches', ['user_id'], unique=False)
    op.create_table('practice_servers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('vultr_instance_id', sa.String(length=36), nullable=True),
    sa.Column('ip_address', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('rcon_password', sa.String(length=32), nullable=False),
    sa.Column('server_password', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_practice_servers_team_id'), 'practice_servers', ['team_id'], unique=False)
    op.create_table('team_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_members_team_id'), 'team_members', ['team_id'], unique=False)
    op.create_index(op.f('ix_team_members_user_id'), 'team_members', ['user_id'], unique=False)
    op.create_table('team_playbooks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('map_name', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('playbook_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_playbooks_map_name'), 'team_playbooks', ['map_name'], unique=False)
    op.create_index(op.f('ix_team_playbooks_team_id'), 'team_playbooks', ['team_id'], unique=False)
    op.create_table('first_contacts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('round_num', sa.Integer(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('attacker', sa.String(length=64), nullable=False),
    sa.Column('attacker_team', sa.String(length=64), nullable=False),
    sa.Column('victim', sa.String(length=64), nullable=False),
    sa.Column('weapon', sa.String(length=32), nullable=False),
    sa.Column('headshot', sa.Boolean(), nullable=False),
    sa.Column('attacker_steamid', sa.String(length=32), nullable=True),
    sa.Column('victim_steamid', sa.String(length=32), nullable=True),
    sa.Column('attacker_x', sa.Float(), nullable=False),
    sa.Column('attacker_y', sa.Float(), nullable=False),
    sa.Column('victim_x', sa.Float(), nullable=False),
    sa.Column('victim_y', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_first_contacts_match_id'), 'first_contacts', ['match_id'], unique=False)
    op.create_table('grenades',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('round_num', sa.Integer(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('thrower', sa.String(length=64), nullable=False),
    sa.Column('team', sa.String(length=64), nullable=False),
    sa.Column('grenade_type', sa.String(length=32), nullable=False),
    sa.Column('throw_x', sa.Float(), nullable=False),
    sa.Column('throw_y', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_grenades_match_id'), 'grenades', ['match_id'], unique=False)
    op.create_table('kills',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('round_num', sa.Integer(), nullable=False),
    sa.Column('tick', sa.Integer(), nullable=False),
    sa.Column('attacker', sa.String(length=64), nullable=False),
    sa.Column('attacker_team', sa.String(length=64), nullable=False),
    sa.Column('victim', sa.String(length=64), nullable=False),
    sa.Column('victim_team', sa.String(length=64), nullable=False),
    sa.Column('weapon', sa.String(length=32), nullable=False),
    sa.Column('headshot', sa.Boolean(), nullable=False),
    sa.Column('attacker_steamid', sa.String(length=32), nullable=True),
    sa.Column('victim_steamid', sa.String(length=32), nullable=True),
    sa.Column('attacker_x', sa.Float(), nullable=False),
    sa.Column('attacker_y', sa.Float(), nullable=False),
    sa.Column('attacker_z', sa.Float(), nullable=False),
    sa.Column('victim_x', sa.Float(), nullable=False),
    sa.Column('victim_y', sa.Float(), nullable=False),
    sa.Column('victim_z', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kills_match_id'), 'kills', ['match_id'], unique=False)
    op.create_table('rounds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('round_num', sa.Integer(), nullable=False),
    sa.Column('winner_side', sa.String(length=64), nullable=False),
    sa.Column('reason', sa.String(length=64), nullable=False),
    sa.Column('ct_eq_val', sa.Integer(), nullable=False),
    sa.Column('t_eq_val', sa.Integer(), nullable=False),
    sa.Column('ct_score', sa.Integer(), nullable=False),
    sa.Column('t_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rounds_match_id'), 'rounds', ['match_id'], unique=False)
    op.create_table('training_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('team_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=64), nullable=False),
    sa.Column('server_id', sa.String(length=36), nullable=True),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('map_name', sa.String(length=64), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('job_id', sa.String(length=36), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['matches.match_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['server_id'], ['practice_servers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_training_sessions_job_id'), 'training_sessions', ['job_id'], unique=False)
    op.create_index(op.f('ix_training_sessions_team_id'), 'training_sessions', ['team_id'], unique=False)
    op.create_index(op.f('ix_training_sessions_user_id'), 'training_sessions', ['user_id'], unique=False)
    op.create_table('trajectories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=36), nullable=False),
    sa.Column('round_num', sa.Integer(), nullable=False),
    sa.Column('player', sa.String(length=64), nullable=False),
    sa.Column('team', sa.String(length=64), nullable=False),
    sa.Column('positions_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.match_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trajectories_match_id'), 'trajectories', ['match_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trajectories_match_id'), table_name='trajectories')
    op.drop_table('trajectories')
    op.drop_index(op.f('ix_training_sessions_user_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_team_id'), table_name='training_sessions')
    op.drop_index(op.f('ix_training_sessions_job_id'), table_name='training_sessions')
    op.drop_table('training_sessions')
    op.drop_index(op.f('ix_rounds_match_id'), table_name='rounds')
    op.drop_table('rounds')
    op.drop_index(op.f('ix_kills_match_id'), table_name='kills')
    op.drop_table('kills')
    op.drop_index(op.f('ix_grenades_match_id'), table_name='grenades')
    op.drop_table('grenades')
    op.drop_index(op.f('ix_first_contacts_match_id'), table_name='first_contacts')
    op.drop_table('first_contacts')
    op.drop_index(op.f('ix_team_playbooks_team_id'), table_name='team_playbooks')
    op.drop_index(op.f('ix_team_playbooks_map_name'), table_name='team_playbooks')
    op.drop_table('team_playbooks')
    op.drop_index(op.f('ix_team_members_user_id'), table_name='team_members')
    op.drop_index(op.f('ix_team_members_team_id'), table_name='team_members')
    op.drop_table('team_members')
    op.drop_index(op.f('ix_practice_servers_team_id'), table_name='practice_servers')
    op.drop_table('practice_servers')
    op.drop_index(op.f('ix_matches_user_id'), table_name='matches')
    op.drop_index(op.f('ix_matches_team_id'), table_name='matches')
    op.drop_table('matches')
    op.drop_index(op.f('ix_user_strategies_user_id'), table_name='user_strategies')
    op.drop_index(op.f('ix_user_strategies_map_name'), table_name='user_strategies')
    op.drop_table('user_strategies')
    op.drop_index(op.f('ix_teams_owner_user_id'), table_name='teams')
    op.drop_index(op.f('ix_teams_invite_code'), table_name='teams')
    op.drop_table('teams')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_map_playbooks_map_name'), table_name='map_playbooks')
    op.drop_table('map_playbooks')
    op.drop_index(op.f('ix_linked_accounts_user_id'), table_name='linked_accounts')
    op.drop_table('linked_accounts')
    op.drop_index(op.f('ix_knowledge_embeddings_source'), table_name='knowledge_embeddings')
    op.drop_table('knowledge_embeddings')
    # ### end Alembic commands ###
